version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: postgresContainer
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5433:5432'
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql